spring:
  application:
    name: notification

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 71f2ea5b449b22
    password: 642186110f5494

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: flight-management-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true

server:
  port: 8084


